<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RootNamespace>FeigScan</RootNamespace>
    <AssemblyName>FeigScan</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\FeigDotNet\FeigDotNet.csproj" />
  </ItemGroup>
</Project>
